apiVersion: v1
kind: Service
metadata:
  name: jellyfish-trainingportal-redis-svc-stg
  namespace: jellyfish-trainingportal-ns-stg
  labels:
    app: jellyfish-trainingportal-redis-svc-stg
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: jellyfish-trainingportal-redis-stg
    env: jellyfish-trainingportal-stg
